require("autocommands")
require("colorscheme")
require("keymappings")
require("nvim-providers")
require("options")
require("plugins")

require("plugin-config.alpha")
require("plugin-config.autopairs")
require("plugin-config.bufferline")
require("plugin-config.cmp")
require("plugin-config.comment")
require("plugin-config.gitsigns")
require("plugin-config.impatient")
require("plugin-config.indentline")
require("plugin-config.lualine")
require("plugin-config.notify")
require("plugin-config.nvim-tree")
require("plugin-config.project")
require("plugin-config.telescope")
require("plugin-config.toggleterm")
require("plugin-config.treesitter")
require("plugin-config.which-key")

require("lsp")
